import fs from 'node:fs';
import path from 'node:path';
import yaml from 'yaml';

export function writeEnv(filePath, vars) {
  const lines = [
    '# Generated by: npm run setup:wechat-supplier',
    `# ${new Date().toISOString()}`,
    '',
  ];
  for (const [key, value] of Object.entries(vars)) {
    if (value === undefined || value === null) continue;
    lines.push(`${key}=${String(value)}`);
  }
  lines.push('');
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
}

export function writeRegistry(filePath, { defaults, suppliers, internal }) {
  const doc = {
    version: '1.0',
    defaults,
    suppliers,
    internal: internal || {
      procurementDigestConversationId: 'internal:procurement',
    },
  };
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, yaml.stringify(doc), 'utf8');
}

export function writeManifest(filePath, manifest) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
}

export function writeOpenClawSnippet(filePath, { extraDir, repoRoot }) {
  const content = `{
  // 由 setup:wechat-supplier 生成 · 合并进 ~/.openclaw/openclaw.json
  "skills": {
    "load": {
      "extraDirs": [
        "${extraDir.replace(/\\/g, '/')}"
      ]
    },
    "entries": {
      "wechat-supplier-collab": {
        "enabled": true
      }
    }
  },
  "channels": {
    "rest": {
      "enabled": true,
      "accounts": {
        "default": {
          "webhookUrl": "http://127.0.0.1:8787/openclaw/outbound",
          "inboundApiKey": "见 wechaty-bridge/.env 中 OPENCLAW_INBOUND_API_KEY",
          "webhookSecret": "见 wechaty-bridge/.env 中 OPENCLAW_WEBHOOK_SECRET"
        }
      }
    }
  },
  "agents": {
    "defaults": {
      "skills": ["wechat-supplier-collab"]
    }
  },
  "_setupNote": "仓库路径 ${repoRoot.replace(/\\/g, '/')}"
}
`;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}
